services:
    app:
        image: ghcr.io/kuasar-mknd/gym-tracker:latest
        restart: always
        ports:
            - 8888:80
        environment:
            APP_KEY: base64:obdMrKq+1Px1qLiAP3KMDFCwpINE/2qgr7eTvNRQVrQ=
            APP_URL: https://fit.kuasar.xyz
            APP_ENV: production
            APP_DEBUG: false
            DB_CONNECTION: mysql
            DB_HOST: db
            DB_PORT: 3306
            DB_DATABASE: gym_tracker
            DB_USERNAME: gym_user
            DB_PASSWORD: Gym2026SecurePass!
            REDIS_HOST: redis
            REDIS_PASSWORD: Redis2026SecurePass!
            REDIS_PORT: 6379
            OCTANE_SERVER: frankenphp
            SESSION_DRIVER: redis
            CACHE_STORE: redis
            QUEUE_CONNECTION: redis
        links:
            - db
            - redis
        depends_on:
            - db
            - redis

    db:
        image: mysql:8.0
        restart: always
        environment:
            MYSQL_DATABASE: gym_tracker
            MYSQL_USER: gym_user
            MYSQL_PASSWORD: Gym2026SecurePass!
            MYSQL_ROOT_PASSWORD: GymRoot2026SecurePass!
        volumes:
            - db_data:/var/lib/mysql
        command: --default-authentication-plugin=mysql_native_password

    redis:
        image: redis:alpine
        restart: always
        command: redis-server --requirepass Redis2026SecurePass!
        volumes:
            - redis_data:/data

    worker:
        image: ghcr.io/kuasar-mknd/gym-tracker:latest
        restart: always
        command: php artisan horizon
        environment:
            APP_KEY: base64:obdMrKq+1Px1qLiAP3KMDFCwpINE/2qgr7eTvNRQVrQ=
            APP_ENV: production
            DB_CONNECTION: mysql
            DB_HOST: db
            DB_PORT: 3306
            DB_DATABASE: gym_tracker
            DB_USERNAME: gym_user
            DB_PASSWORD: Gym2026SecurePass!
            REDIS_HOST: redis
            REDIS_PASSWORD: Redis2026SecurePass!
            REDIS_PORT: 6379
            QUEUE_CONNECTION: redis
        links:
            - db
            - redis
        depends_on:
            - db
            - redis

volumes:
    db_data:
    redis_data:
